code --install-extension adpyke.codesnap
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dracula-theme.theme-dracula
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-rename-tag
code --install-extension GraphQL.vscode-graphql
code --install-extension JakeWilson.vscode-cdnjs
code --install-extension jeff-hykin.better-dockerfile-syntax
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension syler.sass-indented
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons

#olaaaa
code --install-extension adpyke.codesnap
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dracula-theme.theme-dracula
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-rename-tag
code --install-extension GraphQL.vscode-graphql
code --install-extension JakeWilson.vscode-cdnjs
code --install-extension jeff-hykin.better-dockerfile-syntax
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension syler.sass-indented
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
